vich_uploader:
    db_driver: orm

    mappings:
        player_image:
            uri_prefix: /images/players
            upload_destination: '%kernel.project_dir%/public/images/players'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
